name: Tagged
options:
  bundleIdPrefix: co.pointfree
  deploymentTarget:
    iOS: 8.0
    macOS: 10.9
    tvOS: 9.0
    watchOS: 2.0
  indentWidth: 2
  tabWidth: 2
  usesTabs: false
targets:
  Tagged:
    info:
      path: Info.plist
    platform: [macOS, iOS, tvOS, watchOS]
    scheme:
      testTargets: [TaggedTests_$platform]
    sources: [Sources/Tagged]
    type: framework
  TaggedTests:
    dependencies: [{target: Tagged_$platform}]
    platform: [macOS, iOS, tvOS, watchOS]
    sources:
      - path: Tests/TaggedTests
    type: bundle.unit-test
  TaggedMoney:
    dependencies: [{target: Tagged_$platform}]
    info:
      path: Info.plist
    platform: [macOS, iOS, tvOS, watchOS]
    scheme:
      testTargets: [TaggedMoneyTests_$platform]
    sources: [Sources/TaggedMoney]
    type: framework
  TaggedMoneyTests:
    dependencies: [{target: TaggedMoney_$platform}]
    platform: [macOS, iOS, tvOS, watchOS]
    sources:
      - path: Tests/TaggedMoneyTests
    type: bundle.unit-test
  TaggedTime:
    dependencies: [{target: Tagged_$platform}]
    info:
      path: Info.plist
    platform: [macOS, iOS, tvOS, watchOS]
    scheme:
      testTargets: [TaggedTimeTests_$platform]
    sources: [Sources/TaggedTime]
    type: framework
  TaggedTimeTests:
    dependencies: [{target: TaggedTime_$platform}]
    platform: [macOS, iOS, tvOS, watchOS]
    sources:
      - path: Tests/TaggedTimeTests
    type: bundle.unit-test
