#if !canImport(ObjectiveC)
import XCTest

extension TaggedTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaggedTimeTests = [
        ("testDate", testDate),
        ("testLossyMillisecondsToSeconds", testLossyMillisecondsToSeconds),
        ("testMillisecondsSince", testMillisecondsSince),
        ("testMillisecondsToDate", testMillisecondsToDate),
        ("testMillisecondsToSeconds", testMillisecondsToSeconds),
        ("testMillisecondsToTimeInterval", testMillisecondsToTimeInterval),
        ("testSecondsSince", testSecondsSince),
        ("testSecondsToMilliseconds", testSecondsToMilliseconds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TaggedTimeTests.__allTests__TaggedTimeTests),
    ]
}
#endif
