#if !canImport(ObjectiveC)
import XCTest

extension TaggedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaggedTests = [
        ("testCoerce", testCoerce),
        ("testComparable", testComparable),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testDecodable", testDecodable),
        ("testDecodableCustomDates", testDecodableCustomDates),
        ("testEncodable", testEncodable),
        ("testEncodableCustomDates", testEncodableCustomDates),
        ("testEquatable", testEquatable),
        ("testError", testError),
        ("testExpressibleByBooleanLiteral", testExpressibleByBooleanLiteral),
        ("testExpressibleByFloatLiteral", testExpressibleByFloatLiteral),
        ("testExpressibleByIntegerLiteral", testExpressibleByIntegerLiteral),
        ("testExpressibleByStringLiteral", testExpressibleByStringLiteral),
        ("testHashable", testHashable),
        ("testLocalizedError", testLocalizedError),
        ("testLosslessStringConvertible", testLosslessStringConvertible),
        ("testMap", testMap),
        ("testNumeric", testNumeric),
        ("testOptionalRawTypeAndNilValueDecodesCorrectly", testOptionalRawTypeAndNilValueDecodesCorrectly),
        ("testOptionalRawTypeAndNilValueEncodesCorrectly", testOptionalRawTypeAndNilValueEncodesCorrectly),
        ("testSignedNumeric", testSignedNumeric),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TaggedTests.__allTests__TaggedTests),
    ]
}
#endif
