#if !canImport(ObjectiveC)
import XCTest

extension TaggedTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaggedTimeTests = [
        ("testCentsToDollars", testCentsToDollars),
        ("testDollarsToCents", testDollarsToCents),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TaggedTimeTests.__allTests__TaggedTimeTests),
    ]
}
#endif
