name: CI

on: [push]

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: make test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: make test-linux
