name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: macOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: Run tests
      run: swift test

  linux:
    strategy:
      matrix:
        swift:
          - '5.10'
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test --parallel
      - name: Run tests (release)
        run: swift test -c release --parallel
